In [38]:
import numpy as np
print(np.__version__)

2.4.1


In [ ]:
# importing numpy
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
print(arr)

[[1 2 3 4 5 6]]


In [ ]:
#specify minimum dimensions
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6], ndmin = 2)
print(arr)

[[1 2 3 4 5 6]]


In [17]:
#specify data type
import numpy as np
arr = np.array([1, 2, 3, 4], dtype = str)
print(arr)


['1' '2' '3' '4']


In [10]:
import numpy as np
a = np.array([[1,2,4],[5,0,4]])
print("original array",a)
print("shape of array",a.shape)
print("stride of array",a.strides)


original array [[1 2 4]
 [5 0 4]]
shape of array (2, 3)
stride of array (24, 8)


In [1]:
import numpy as np
speed =[86,87,88,86,87,85,86]
x = np.std(speed)
print(x)

0.9035079029052513


In [43]:
import numpy as np
arr = np.array([32])
arr.ndim


1

In [7]:
import numpy as np
# create a range of numbers from 0 to 10
range = np.arange(0, 10)
print(range)

[0 1 2 3 4 5 6 7 8 9]


In [12]:
# evenly spaced numbers
arr = np.linspace(1, 0.5, 5)
print(arr)

[1.    0.875 0.75  0.625 0.5  ]


In [14]:
#logspaced numbers
arr = np.logspace(1, 3, 3)
print(arr)

[  10.  100. 1000.]


In [16]:
zero = np.zeros((2,3))
zero

array([[0., 0., 0.],
       [0., 0., 0.]])

In [28]:
# create an array of shape (10,2) filled with 2
#arr = np.full([2, 2], 1)
#arr

value = np.full(5,2)
value

array([2, 2, 2, 2, 2])

In [30]:
# random
arr = np.random.rand(2,2)
arr

array([[0.55228589, 0.55677741],
       [0.71195809, 0.00107361]])

In [37]:
arr = np.random.randint(12,50)
arr

26

In [41]:
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a+b)

[5 7 9]


In [44]:
import numpy as np
np.empty((3,2))

array([[0.09115372, 0.59652813],
       [0.20420317, 0.33748894],
       [0.58548691, 0.79496875]])

In [46]:
import numpy as np
arr = np.arange(0,10,2)
print(arr)

[0 2 4 6 8]


In [49]:
from numpy import pi
print(np.linspace(0,2,9)) # 9 numbers from 0 to 2
x = np.linspace(0,2*pi,100) # 100 numbers from 0 to 2pi
f = print(np.sin(x))

[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]
[ 0.00000000e+00  6.34239197e-02  1.26592454e-01  1.89251244e-01
  2.51147987e-01  3.12033446e-01  3.71662456e-01  4.29794912e-01
  4.86196736e-01  5.40640817e-01  5.92907929e-01  6.42787610e-01
  6.90079011e-01  7.34591709e-01  7.76146464e-01  8.14575952e-01
  8.49725430e-01  8.81453363e-01  9.09631995e-01  9.34147860e-01
  9.54902241e-01  9.71811568e-01  9.84807753e-01  9.93838464e-01
  9.98867339e-01  9.99874128e-01  9.96854776e-01  9.89821442e-01
  9.78802446e-01  9.63842159e-01  9.45000819e-01  9.22354294e-01
  8.95993774e-01  8.66025404e-01  8.32569855e-01  7.95761841e-01
  7.55749574e-01  7.12694171e-01  6.66769001e-01  6.18158986e-01
  5.67059864e-01  5.13677392e-01  4.58226522e-01  4.00930535e-01
  3.42020143e-01  2.81732557e-01  2.20310533e-01  1.58001396e-01
  9.50560433e-02  3.17279335e-02 -3.17279335e-02 -9.50560433e-02
 -1.58001396e-01 -2.20310533e-01 -2.81732557e-01 -3.42020143e-01
 -4.00930535e-01 -4.58226522e-01 -5.1367739