In [ ]:
# importing numpy 
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
print(arr)

[[1 2 3 4 5 6]]


In [ ]:
#specify minimum dimensions
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6], ndmin = 2)
print(arr)

[[1 2 3 4 5 6]]


In [5]:
#specify data type
import numpy as np
arr = np.array([1, 2, 3, 4], dtype = complex)
print(arr)


[1.+0.j 2.+0.j 3.+0.j 4.+0.j]


In [10]:
import numpy as np
a = np.array([[1,2,4],[5,0,4]])
print("original array",a)
print("shape of array",a.shape)
print("stride of array",a.strides)


original array [[1 2 4]
 [5 0 4]]
shape of array (2, 3)
stride of array (24, 8)


In [1]:
import numpy as np
speed =[86,87,88,86,87,85,86]
x = np.std(speed)
print(x)

0.9035079029052513
