In [ ]:
# importing numpy 
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
print(arr)

[[1 2 3 4 5 6]]


In [ ]:
#specify minimum dimensions
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6], ndmin = 2)
print(arr)

[[1 2 3 4 5 6]]


In [17]:
#specify data type
import numpy as np
arr = np.array([1, 2, 3, 4], dtype = str)
print(arr)


['1' '2' '3' '4']


In [10]:
import numpy as np
a = np.array([[1,2,4],[5,0,4]])
print("original array",a)
print("shape of array",a.shape)
print("stride of array",a.strides)


original array [[1 2 4]
 [5 0 4]]
shape of array (2, 3)
stride of array (24, 8)


In [1]:
import numpy as np
speed =[86,87,88,86,87,85,86]
x = np.std(speed)
print(x)

0.9035079029052513


In [4]:
import numpy as np
arr = np.array([32])
arr.ndim

1

In [7]:
import numpy as np
# create a range of numbers from 0 to 10
range = np.arange(0, 10)
print(range)

[0 1 2 3 4 5 6 7 8 9]


In [12]:
# evenly spaced numbers
arr = np.linspace(1, 0.5, 5)
print(arr)

[1.    0.875 0.75  0.625 0.5  ]


In [14]:
#logspaced numbers
arr = np.logspace(1, 3, 3)
print(arr)

[  10.  100. 1000.]


In [16]:
zero = np.zeros((2,3))
zero

array([[0., 0., 0.],
       [0., 0., 0.]])

In [20]:
#create a array of 10 elements default is 2
arr= np.full((10,2))
arr

TypeError: full() missing 1 required positional argument: 'fill_value'