In [5]:
# Numpy arrays
# 1. numpy.array()

import numpy as np
arr = np.array([1, 2, 3, 4, 5])
two_arr = np.array([[1, 2, 3], [4, 5, 6]])
print("1-D Array:",arr)
print("2-D Array:\n",two_arr)


1-D Array: [1 2 3 4 5]
2-D Array:
 [[1 2 3]
 [4 5 6]]


In [7]:
import numpy as np
a = np.zeros((2,2))
print(a)

[[0. 0.]
 [0. 0.]]


In [12]:
import numpy as np
a = np.ones(2)
print(a)

[1. 1.]


In [13]:
# creating fortran-ordered array
import numpy as np
a = np.ones((3,4), order='F')
print(a)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [16]:
import numpy as np
arr = np.arange(5)
print(arr)
arr2=np.arange(2,10,3)
print(arr2)

[0 1 2 3 4]
[2 5 8]


In [18]:
import numpy as np
arr1 = np.random.rand()
print(arr1)

arr2= np.random.rand(1,2)
print("Random array2 is :\n",arr1)

arr3 = np.random.rand(2,3,4)
print("Random array3 is :\n",arr3)

0.7469397236528743
Random array2 is :
 0.7469397236528743
Random array3 is :
 [[[0.33004562 0.19209275 0.72684984 0.0457355 ]
  [0.73148161 0.54383673 0.87865643 0.68442396]
  [0.53885104 0.69824869 0.25747762 0.52136208]]

 [[0.82153134 0.4205576  0.22814516 0.64593873]
  [0.57974542 0.44391704 0.82239077 0.40871139]
  [0.95435557 0.36809579 0.69322917 0.20517071]]]


In [ ]:
arr =np.full((2,2),7)
print("Full array:\n",arr)
print("Full array:\n",arr)


Full array:
 [[7 7]
 [7 7]]
